// <auto-generated />
namespace HappyLifeManagement.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update2004201701 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update2004201701));
        
        string IMigrationMetadata.Id
        {
            get { return "201704201200122_Update2004201701"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
