// <auto-generated />
namespace HappyLifeManagement.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update12042017_01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update12042017_01));
        
        string IMigrationMetadata.Id
        {
            get { return "201704121404299_Update12042017_01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
